python main_gt_loss.py --task sts-b --tau 0
python main_gt_loss.py --task sts-b --tau 0.1
python main_gt_loss.py --task sts-b --tau 0.2
python main_gt_loss.py --task sts-b --tau 0.3
python main_gt_loss.py --task sts-b --tau 0.4
python main_gt_loss.py --task sts-b --tau 0.5
python main_gt_loss.py --task sts-b --tau 0.6
python main_gt_loss.py --task sts-b --tau 0.7
python main_gt_loss.py --task sts-b --tau 0.8
python main_gt_loss.py --task sts-b --tau 0.9
python main_gt_loss.py --task sts-b --tau 1
